/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PengelolaanKRS;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.EventObject;



/**
 *
 * @author achma
 */
public class TransaksiKRSGUI extends javax.swing.JFrame {
    
    
    private void biaya() {
    if (combojurusan.getSelectedItem().equals("Teknik Informatika")) {
        int biaya = 32499000;
        textbiaya.setText(Integer.toString(biaya));
    } else if (combojurusan.getSelectedItem().equals("Sistem Informatika")) {
        int biaya = 2950000;
        textbiaya.setText(Integer.toString(biaya));

    } else if (combojurusan.getSelectedItem().equals("Hukum")) {
        int biaya = 42499000;
        textbiaya.setText(Integer.toString(biaya));
    
    } else if (combojurusan.getSelectedItem().equals("Ekonomi Syariah")) {
       int biaya = 30299000;
       textbiaya.setText(Integer.toString(biaya));

    } else if (combojurusan.getSelectedItem().equals("Politik Dan Hukum")) {
        int biaya = 2920000;
        textbiaya.setText(Integer.toString(biaya));
    
    } else if (combojurusan.getSelectedItem().equals("Hubungan Internasional")) {
        int biaya = 2850000;
        textbiaya.setText(Integer.toString(biaya));
    
        
    }
}

    private void hitung() {
    double biayapermalam, totalbiaya, totalseluruh, persemester, pajak;

    biayapermalam = Double.parseDouble(textbiaya.getText());
    persemester = Double.parseDouble(textpersemester.getText());

    totalbiaya = biayapermalam * persemester;
    texttotal.setText(String.valueOf(totalbiaya));

    pajak = 11 * totalbiaya / 100;
    totalseluruh = totalbiaya + pajak;
    textkeseluruhan.setText(String.valueOf(totalseluruh));

    textpajak.setText(String.valueOf(pajak));
    textbiaya.setText(String.valueOf(biayapermalam));
    textpersemester.setText(String.valueOf(persemester));
}

            
 
    private void kosongkan_form(){
    textpersemester.setEditable(true);
    textpersemester.setText(null);
    combojurusan.setSelectedItem(this);
    textbiaya.setText(null);
    texttotal.setText(null);
    textpajak.setText(null);
    textkeseluruhan.setText(null);
    }
     
     
     private void tampil_data(){
         
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Jurusan");
        model.addColumn("Per Semester");
        model.addColumn("Biaya");
        model.addColumn("Total");
        model.addColumn("Pajak");
        model.addColumn("Total Keseluruhan");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM transaksi";
            java.sql.Connection conn=(Connection)koneksidb.databaseDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)});
            }
            tabeltransaksi.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
     }
    /**
     * Creates new form TransaksiKRSGUI
     */
    public TransaksiKRSGUI() {
        initComponents();
        tampil_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textpersemester = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        textbiaya = new javax.swing.JTextField();
        ButtonTambah = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        combojurusan = new javax.swing.JComboBox<>();
        textcari = new javax.swing.JTextField();
        ButtonCetak = new javax.swing.JButton();
        texttotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textpajak = new javax.swing.JTextField();
        textkeseluruhan = new javax.swing.JTextField();
        ButtonHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSAKSI KRS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel2.setText("PER SEMESTER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel3.setText("BIAYA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel4.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel4.setText("JURUSAN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLabel5.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel5.setText("TOTAL BIAYA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel6.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel6.setText("TOTAL KESELURUHAN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, 30));

        jLabel8.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel8.setText("Ketik disni untuk mencari data Transaksi");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));
        jPanel2.add(textpersemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 11, 164, -1));

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltransaksi);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 550, 290));

        textbiaya.setEnabled(false);
        jPanel2.add(textbiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 164, -1));

        ButtonTambah.setText("TAMBAHKAN");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        ButtonHapus.setText("HAPUS");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, -1));

        ButtonBatal.setText("BATAL");
        ButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatalActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 93, -1));

        ButtonKembali.setText("KEMBALI");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        ButtonExit.setText("EXIT");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 93, -1));

        combojurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Jurusan ---", "Teknik Informatika", "Sistem Informatika", "Hukum", "Ekonomi Syariah", "Politik Dan Hukum", "Hubungan Internasional" }));
        combojurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combojurusanActionPerformed(evt);
            }
        });
        combojurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combojurusanKeyReleased(evt);
            }
        });
        jPanel2.add(combojurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, -1));

        textcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textcariKeyReleased(evt);
            }
        });
        jPanel2.add(textcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 240, -1));

        ButtonCetak.setText("CETAK");
        ButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCetakActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, -1, -1));

        texttotal.setEnabled(false);
        jPanel2.add(texttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 164, -1));

        jLabel7.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel7.setText("PAJAK 11%");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        textpajak.setEnabled(false);
        jPanel2.add(textpajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, -1));

        textkeseluruhan.setEnabled(false);
        jPanel2.add(textkeseluruhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, -1));

        ButtonHitung.setText("HITUNG");
        ButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitungActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tabeltransaksi.rowAtPoint(evt.getPoint());

        String per1 = tabeltransaksi.getValueAt(baris, 1).toString();
        textpersemester.setText(per1);

        String jrusan = tabeltransaksi.getValueAt(baris, 2).toString();
        combojurusan.setSelectedItem(jrusan);

        String semester = tabeltransaksi.getValueAt(baris, 3).toString();
        textbiaya.setText(semester);

        String ttlbiaya = tabeltransaksi.getValueAt(baris, 4).toString();
        texttotal.setText(ttlbiaya);
        
        String pajak = tabeltransaksi.getValueAt(baris, 5).toString();
        textpajak.setText(pajak);
        
        String totalsluruh = tabeltransaksi.getValueAt(baris, 6).toString();
        textkeseluruhan.setText(totalsluruh);
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO transaksi VALUES ('"+textpersemester.getText()+"','"+combojurusan.getSelectedItem()+"','"+textbiaya.getText()+"','"+texttotal.getText()+"','"+textpajak.getText()+"','"+textkeseluruhan.getText()+"')";
            java.sql.Connection conn = (Connection)koneksidb.databaseDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Tambah Data Transaksi Berhasil!");
            tampil_data();
            kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM transaksi WHERE per_semester='"+textpersemester.getText()+"'";
            java.sql.Connection conn= (Connection)koneksidb.databaseDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Transaksi Berhasil!");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosongkan_form();
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        PengelolaanKRSMenu var;
        var = new PengelolaanKRSMenu();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void textcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Jurusan");
        model.addColumn("Per Semester");
        model.addColumn("Biaya");
        model.addColumn("Total");
        model.addColumn("Pajak");
        model.addColumn("Total Keseluruhan");
        try{
            int no = 1;
            String sql = "SELECT * FROM transaksi WHERE jurusan LIKE '%"+textcari.getText()+"%'";
            java.sql.Connection conn=(Connection)koneksidb.databaseDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            tabeltransaksi.setModel(model);

        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_textcariKeyReleased

    private void ButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCetakActionPerformed
        // TODO add your handling code here:
        java.io.File namafile=new java.io.File("./reporttransaksi.jasper");
        try{
            net.sf.jasperreports.engine.JasperReport jasper;
            jasper=(net.sf.jasperreports.engine.JasperReport)
            net.sf.jasperreports.engine.util.JRLoader.loadObject(namafile.getPath());
            net.sf.jasperreports.engine.JasperPrint jp;
            jp=net.sf.jasperreports.engine.JasperFillManager.fillReport(jasper, null, koneksidb.databaseDB());
            net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonCetakActionPerformed

    private void ButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitungActionPerformed
        // TODO add your handling code here:
        hitung();
    }//GEN-LAST:event_ButtonHitungActionPerformed

    private void combojurusanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combojurusanKeyReleased
        // TODO add your handling code here:
        //combojurusanSelectedIndexChanged();
    }//GEN-LAST:event_combojurusanKeyReleased

    private void combojurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combojurusanActionPerformed
        // TODO add your handling code here:
        biaya();
    }//GEN-LAST:event_combojurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiKRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiKRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiKRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiKRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiKRSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonCetak;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JComboBox<String> combojurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField textbiaya;
    private javax.swing.JTextField textcari;
    private javax.swing.JTextField textkeseluruhan;
    private javax.swing.JTextField textpajak;
    private javax.swing.JTextField textpersemester;
    private javax.swing.JTextField texttotal;
    // End of variables declaration//GEN-END:variables
}
